### ISSUE TITLE
Preview images don't show for nested flexible content

### ISSUE THREAD

**Issue by adammontague** [jameelmoses/acf-flexible-content-preview#2]
#### Version information

* Plugin version : 1.0.0
* ACF version : 5.8.4
* PHP : 7.2
* WordPress : 5.2.3

#### Steps to reproduce

1. Create an overall flexible content field
2. Create a repeater field inside the flexible content
3. Create a further flexible content field inside the repeater.

#### What was expected
I was expecting to see the preview images for the sub-flexible content as per normal. 

#### What happened instead
No images appear for the sub-flexible content, they do appear for the overall "parent" flexible content.

**Comment by jameelmoses** [comment]
Apologies for the delayed response. I know it’s not what you want to hear, but I haven’t needed to next flexible content fields that way, so I didn’t test or develop against those requirements. I’d be happy to review a PR adding support for nesting if you’re interested in contributing.

**Comment by paulmist** [comment]
#4

**Comment by jameelmoses** [comment]
This has been resolved in v1.0.2
