### ISSUE TITLE
PHP8.0 Warnings On Singleton Class

### ISSUE THREAD

**Issue by elliottpost** [jameelmoses/acf-flexible-content-preview#23]
#### Version information

* Plugin version : Latest
* ACF version :  Latest
* PHP : 8.0+
* WordPress : 5.9+

#### Steps to reproduce

1. Install any version of this plugin on a site running PHP 8+
2. Ensure `WP_DEBUG` is `true` and `WP_DEBUG_LOG` is `true`
3. Check error log for issues

#### What was expected
Plugin to run without warnings

#### What happened instead
Plugin has PHP errors due to `final` and `private` being used together in the Singleton class. By definition, a `private` function is `final` because it cannot be overridden by any subclass (only `protected` and `public` methods may be)

**Comment by jameelmoses** [comment]
This plugin has been deprecated in favor of [Flexible Content Extended for Advanced Custom Fields](https://github.com/jameelmoses/acf-flexible-content-extended)
