### ISSUE TITLE
Preview Images Missing

### ISSUE THREAD

**Issue by cmc3502** [jameelmoses/acf-flexible-content-preview#3]
Maybe this is because I'm trying this with WP 5.3? The images are placed in my theme folder/lib/admin/images/acf-flexible-content-preview/

**Comment by jameelmoses** [comment]
What ACF version are you using?

Are there any errors in the console or 404 errors in the network tab?

Can you please provide the name for the layout and the corresponding image file name?

**Comment by lesliebuying** [comment]
I have the same issue since the update to WP 5.3 :(

Do you know how to fix this?

**Comment by jameelmoses** [comment]
@cmc3502 Can you also please provide the above? I’ll see if I can replicate it in the meantime.

**Comment by cmc3502** [comment]
5.8.7 PRO

Uncaught TypeError: $ is not a function
    at acf-flexible-content-preview.js?ver=1.0.5:2
aioseop-preview-snippet.js?ver=3.3.3:43

strategy was the slug and strategy.jpg was in place.


*Colin Coolidge*
Creative Director

*(214) 295-5165* <214-295-5165>
*modassicmarketing.com* <http://modassicmarketing.com/>

**Comment by andrenoel** [comment]
in acf-flexible-content-preview\assets\js\acf-flexible-content-preview.js
change $() sign to jQuery()

**Comment by jameelmoses** [comment]
This has now been resolved and new releases have been pushed to this Github repository, as well as a new release in the WP plugin directory. Thank you for bringing this issue to my attention.
