### ISSUE TITLE
Custom images are not seeked

### ISSUE THREAD

**Issue by Djibdjib** [jameelmoses/acf-flexible-content-preview#6]
#### Version information

* Plugin version : 1.0.3
* ACF version : 5.8
* PHP : 7.3
* WordPress : 5.4.1

#### Steps to reproduce

1. add_filter('acf-flexible-content-preview.images_path', "dist/images/fcp");
2. add_filter('acf-flexible-content-preview.images_path', function() { return "dist/images/fcp"; });
3. I use a child theme

#### What was expected
1 returns an add_filter error callback function
2 do not show my images

Thx for your help !

**Comment by jameelmoses** [comment]
Thanks for reporting, @Djibdjib. Can you post the exact error with the full stacktrace please? As an FYI, I've never tested the plugin with child themes.

**Comment by Djibdjib** [comment]
Hi ! thx for your answer, i do not have an error message, i think that your apply_filters is not executed and WP does not return an error for that...

**Comment by Djibdjib** [comment]
Okay @jameelmoses ! while reading your classes/main.php at line 135, i've found the str_replace wich gave problems to me !

To resume:
- change add_filter like that : add_filter('acf-flexible-content-preview.images_path', function() { return "your/path"; });

- If you have underscore inside your flexible acf name, you have to replace this by a dashe.

See you and thx for your job !

**Comment by jameelmoses** [comment]
@Djibdjib yes, that's documented in the readme.

> They should be named based on the layout's name (text_block) with underscores converted to dashes (text-block.jpg).

Everything working as expected now?

**Comment by Djibdjib** [comment]
Yes, that's perfect ! do not forget to change add_filter instruction like in my previous post.

Thx a lot !

Regards

**Comment by jameelmoses** [comment]
Great to hear! Hope you're enjoying the plugin.

**Comment by jameelmoses** [comment]
@Djibdjib you also might want to check out https://github.com/jameelmoses/acf-flexible-content-extended/

It's a the newer version of the plugin where I added additional functionality.
