### ISSUE TITLE
Child theme compatibility

### ISSUE THREAD

**Issue by flchristophe** [jameelmoses/acf-flexible-content-preview#7]
#### Version information

* Plugin version : Last
* ACF version : Last
* PHP : PHP 7.2
* WordPress : Last

#### Steps to reproduce

1. Setup a parent theme and a child theme
2. Add  ACF Flexible preview images in the parent theme (in the defalut path)
3. Activate child theme

#### What was expected

Thumbs should be displayed on Flexible content

#### What happened instead

Thumbs do not displays on Flexible content, path is looking for images in the child theme

**Comment by elliottpost** [comment]
You could do a work around for this using `add_filter( 'acf-flexible-content-preview.images_path', $path );` like:

```php
<?php

add_filter( 'acf-flexible-content-preview.images_path', function() {
 return trailingslashit(get_stylesheet_directory()) . "lib/admin/images/acf-flexible-content-preview";
}, 11);
```

**Comment by jameelmoses** [comment]
Yes, this is why the filters have been provided to customize the path.
